import { parseAbi } from "viem";

export const tokenAbi = parseAbi([
  "function balanceOf(address) view returns (uint256)",
  "function allowance(address,address) view returns (uint256)",
  "function approve(address,uint256) returns (bool)",
  "function faucet()",
]);

export const stakeManagerAbi = parseAbi([
  "function createPosition(uint256 amount) returns (uint256)",
  "function issueCredit(uint256 positionId)",
  "function ownerOf(uint256) view returns (address)",
  "function stakeOf(uint256) view returns (uint256)",
  "event PositionCreated(uint256 indexed positionId,address indexed owner,uint256 amount)",
  "event CreditIssued(uint256 indexed positionId,uint256 expiresAt)",
  "event CreditConsumed(uint256 indexed positionId,uint256 indexed taskId)",
  "event PositionReleased(uint256 indexed positionId,uint256 indexed taskId)",
  "event PositionSlashed(uint256 indexed positionId,uint256 indexed taskId,uint256 amount,address indexed recipient)",
  "event PublicationFeeCharged(uint256 indexed positionId,uint256 indexed taskId,uint256 amount,address indexed recipient)",
  "event EvaluationFeeCharged(uint256 indexed positionId,uint256 indexed taskId,uint256 amount,address indexed recipient)",
  "event LifecycleFeeCharged(uint256 indexed positionId,uint256 indexed taskId,uint8 indexed stage,uint256 stakeBasis,uint256 amount)",
  "event PositionWithdrawn(uint256 indexed positionId,address indexed owner,uint256 amount)",
]);

export const agentRegistryAbi = parseAbi([
  "function register(uint256 positionId)",
  "function registerWithCapabilities(uint256 positionId,uint8 capabilities)",
  "function setActive(bool active)",
  "function agentActive(address) view returns (bool)",
  "function agentCapabilities(address) view returns (uint8)",
  "function isEligibleFor(address,uint8) view returns (bool)",
  "function qualityOf(address,uint8) view returns ((uint16 scoreBps,uint32 outcomeCount,uint8 severeFaults,uint64 cooldownUntil,bool banned))",
  "function qualityMultiplierBps(address,uint8) view returns (uint16)",
  "function selectionWeight(address,uint8) view returns (uint256)",
  "function selectionWeightAt(address,uint8,uint64,uint64) view returns (uint256)",
  "function registryVersion() view returns (uint64)",
  "function outcomeReporterRoles(address) view returns (uint8)",
  "event AgentQualityUpdated(address indexed agent,uint8 indexed role,bytes32 indexed outcomeId,uint16 scoreBps,uint32 outcomeCount,uint8 severeFaults,uint64 cooldownUntil,bool banned,bool success,bool severe,bytes32 evidenceHash)",
  "event AgentQualityOutcomeIgnored(address indexed agent,uint8 indexed role,bytes32 indexed outcomeId,bytes32 evidenceHash,bytes32 reason)",
  "event AgentRoleRehabilitated(address indexed agent,uint8 indexed role,bytes32 indexed evidenceHash)",
  "event RegistrySnapshotAdvanced(uint64 indexed version,bytes32 indexed registryHash)",
  "function agentPosition(address) view returns (uint256)",
  "function isEligible(address) view returns (bool)",
  "function agentCount() view returns (uint256)",
  "function agentAt(uint256) view returns (address)",
  "function registryHash() view returns (bytes32)",
  "event AgentRegistered(address indexed agent,uint256 indexed positionId,uint256 stake)",
  "event AgentCapabilitiesUpdated(address indexed agent,uint8 capabilities)",
  "event AgentStatusUpdated(address indexed agent,bool active)",
]);

export const taskRegistryAbi = parseAbi([
  "function createTaskWithMode(uint256 positionId,bytes32 specHash,uint256 requestedReward,uint8 maxExecutors,uint8 mode) returns (uint256)",
  "function createTaskWithModeAndTesterCapabilities(uint256 positionId,bytes32 specHash,uint256 requestedReward,uint8 maxExecutors,uint8 mode,uint8 requiredTesterCapabilities) returns (uint256)",
  "function taskRequiredTesterCapabilities(uint256 taskId) view returns (uint8)",
  "function finalizeEvaluationPanel(uint256 taskId)",
  "function submitEvaluation(uint256 taskId,bytes32 categoryHash,uint16 difficultyBps,uint32 estimatedHours,uint16 testabilityBps,uint256 recommendedReward,bool approve,bytes32 reportHash)",
  "function finalizeTaskEvaluation(uint256 taskId)",
  "function expireTaskEvaluation(uint256 taskId)",
  "function getTaskEvaluators(uint256 taskId) view returns (address[3])",
  "function evaluationSelections(uint256 taskId) view returns (uint256 selectionBlock,uint256 candidateCount,uint256 deadline,bytes32 candidateSetHash,bytes32 selectionProof,uint8 reportCount,uint8 approveCount,bool panelFinalized)",
  "function evaluationResults(uint256 taskId) view returns (bytes32 categoryHash,uint16 difficultyBps,uint32 estimatedHours,uint16 testabilityBps,uint256 recommendedReward)",
  "function claimTask(uint256 taskId)",
  "function closeTeam(uint256 taskId)",
  "function evictInactiveExecutor(uint256 taskId,address executor)",
  "function executorClaimedAt(uint256 taskId,address executor) view returns (uint256)",
  "function contributionRound(uint256 taskId,address executor) view returns (uint32)",
  "function teamFormationStartedAt(uint256 taskId) view returns (uint256)",
  "function submitContribution(uint256 taskId,bytes32 contributionHash)",
  "function submitWork(uint256 taskId,bytes32 artifactHash)",
  "function getTaskExecutors(uint256 taskId) view returns (address[])",
  "function nextTaskId() view returns (uint256)",
  "function tasks(uint256 taskId) view returns (address publisher,address executor,address tester,uint256 positionId,uint256 requestedReward,uint256 createdAt,bytes32 specHash,bytes32 artifactHash,bytes32 evidenceHash,bytes32 candidateSetHash,bytes32 selectionProof,uint256 testerSelectionBlock,uint256 testerCandidateCount,bytes32 teamHash,uint8 maxExecutors,uint8 executorCount,uint8 contributionCount,uint32 workRound,bool teamClosed,uint8 state)",
  "function requestTester(uint256 taskId)",
  "function finalizeTester(uint256 taskId)",
  "function setVerificationPanel(address panel)",
  "function verificationPanel() view returns (address)",
  "function setCoordinator(address newCoordinator)",
  "function setDisputeResolver(address newResolver)",
  "function taskPublicationFee(uint256 taskId) view returns (uint256)",
  "function finalizeVerificationPanel(uint256 taskId,uint32 workRound,uint8 checkpoint,bool passed,address winner,bytes32 selectedArtifactHash,bytes32 aggregateEvidenceHash,uint16[] executorWeightsBps,address[3] testers,uint16[3] testerRewardWeightsBps)",
  "function getTaskTesters(uint256 taskId) view returns (address[3])",
  "function getTaskExecutorWeightsBps(uint256 taskId) view returns (uint16[])",
  "function review(uint256 taskId,bool accepted,bytes32 reasonHash)",
  "function respondToRejection(uint256 taskId,bytes32 responseHash)",
  "function requestMaintenancePanel(uint256 taskId,uint8 checkpoint)",
  "function resolveRejection(uint256 taskId,bool executorWins,bytes32 resolutionHash)",
  "event TaskCreated(uint256 indexed taskId,address indexed publisher,uint256 indexed positionId,bytes32 specHash)",
  "event TaskExecutionModeSet(uint256 indexed taskId,uint8 mode)",
  "event TaskTesterCapabilitiesSet(uint256 indexed taskId,uint8 requiredCapabilities)",
  "event TaskEvaluationRequested(uint256 indexed taskId,address indexed publisher,uint256 indexed positionId,bytes32 specHash,uint256 selectionBlock,bytes32 candidateSetHash,uint256 candidateCount,uint256 deadline)",
  "event TaskEvaluationFeeCharged(uint256 indexed taskId,uint256 indexed positionId,uint256 amount,address indexed recipient)",
  "event TaskEvaluatorsAssigned(uint256 indexed taskId,address indexed evaluator0,address indexed evaluator1,address evaluator2,bytes32 selectionProof)",
  "event TaskEvaluationSubmitted(uint256 indexed taskId,address indexed evaluator,bool approve,bytes32 indexed categoryHash,bytes32 reportHash)",
  "event TaskEvaluationFinalized(uint256 indexed taskId,bool approved,bytes32 categoryHash,uint16 difficultyBps,uint32 estimatedHours,uint16 testabilityBps,uint256 requestedReward)",
  "event TaskEvaluationExpired(uint256 indexed taskId)",
  "event TaskPublicationFeeCharged(uint256 indexed taskId,uint256 indexed positionId,uint256 amount,address indexed recipient)",
  "event TaskClaimed(uint256 indexed taskId,address indexed executor)",
  "event ExecutorEvicted(uint256 indexed taskId,address indexed executor)",
  "event TeamClosed(uint256 indexed taskId,uint256 executorCount)",
  "event ContributionSubmitted(uint256 indexed taskId,address indexed executor,uint32 indexed workRound,bytes32 contributionHash)",
  "event TeamReady(uint256 indexed taskId,address indexed leadExecutor,uint32 indexed workRound)",
  "event CompetitionReady(uint256 indexed taskId,uint32 indexed workRound,uint256 candidateCount)",
  "event WorkSubmitted(uint256 indexed taskId,bytes32 artifactHash)",
  "event TesterRequested(uint256 indexed taskId,uint256 indexed selectionBlock,bytes32 candidateSetHash,uint256 candidateCount)",
  "event TesterAssigned(uint256 indexed taskId,address indexed tester,bytes32 selectionProof)",
  "event TesterPanelAssigned(uint256 indexed taskId,address indexed tester0,address indexed tester1,address tester2,bytes32 selectionProof,uint32 workRound)",
  "event TestSubmitted(uint256 indexed taskId,bool passed,bytes32 evidenceHash)",
  "event CompetitionResultSubmitted(uint256 indexed taskId,bool passed,address indexed winner,bytes32 artifactHash,bytes32 evidenceHash)",
  "event UserReviewed(uint256 indexed taskId,bool accepted,bytes32 reasonHash)",
  "event RejectionResponded(uint256 indexed taskId,address indexed executor,bytes32 responseHash)",
  "event MaintenanceValidated(uint256 indexed taskId,uint8 indexed checkpoint,bool passed,bytes32 evidenceHash)",
  "event MaintenanceRepairRequested(uint256 indexed taskId,uint8 indexed checkpoint,uint32 indexed workRound,bytes32 evidenceHash)",
  "event MaintenancePanelRequested(uint256 indexed taskId,uint8 indexed checkpoint,uint32 indexed workRound)",
  "event RejectionResolved(uint256 indexed taskId,bool executorWins,bytes32 resolutionHash,uint256 publisherSlash)",
]);

export const verificationPanelAbi = parseAbi([
  "function qualityRegistry() view returns (address)",
  "function commitShard(uint256 taskId,bytes32 commitment)",
  "function revealShard(uint256 taskId,uint16 criterionPassMask,address winner,bytes32 selectedArtifactHash,bytes32 evidenceHash,uint16[] executorWeightsBps,bytes32 salt)",
  "function finalize(uint256 taskId)",
  "function expire(uint256 taskId)",
  "function settleEvaluationOutcomes(uint256 taskId)",
  "function evaluationOutcomesSettled(uint256 taskId) view returns (bool)",
  "function getPanel(uint256 taskId) view returns ((address[3] testers,bytes32[3] scopeHashes,uint16[3] criterionMasks,uint16[3] qualityMultipliersBps,uint16 requiredCriterionMask,uint32 epoch,uint32 workRound,uint8 checkpoint,uint8 executorCount,uint8 commitCount,uint8 revealCount,uint64 commitDeadline,uint64 revealDeadline,uint64 challengeDeadline,uint8 status))",
  "function getReport(uint256 taskId,address tester) view returns ((bytes32 commitment,bytes32 evidenceHash,address winner,bytes32 selectedArtifactHash,uint16 criterionPassMask,uint8 commitOrder,bool revealed,uint16[] executorWeightsBps))",
  "function getExecutorQualityMultipliers(uint256 taskId) view returns (uint16[])",
  "event PanelStarted(uint256 indexed taskId,uint32 indexed workRound,uint8 checkpoint,address[3] testers,uint16[3] criterionMasks,bytes32[3] scopeHashes)",
  "event ShardCommitted(uint256 indexed taskId,address indexed tester,uint8 indexed shard,uint32 epoch,uint32 workRound,uint8 commitOrder,bytes32 commitment)",
  "event PanelRevealReady(uint256 indexed taskId,uint32 indexed workRound,uint8 checkpoint,uint32 indexed epoch,address[3] testers)",
  "event ShardRevealed(uint256 indexed taskId,address indexed tester,uint8 indexed shard,uint32 epoch,uint32 workRound,bytes32 evidenceHash,uint16 criterionPassMask)",
  "event PanelAggregated(uint256 indexed taskId,bool passed,bytes32 aggregateEvidenceHash)",
  "event ValidatorRewardWeightsFrozen(uint256 indexed taskId,uint32 indexed workRound,uint8 checkpoint,uint32 indexed epoch,uint16[3] qualityMultipliersBps,uint8[3] commitOrders,uint16[3] finalWeightsBps,uint8 algorithmVersion)",
  "event PanelChallenged(uint256 indexed taskId,address indexed tester,bytes32 challengeHash)",
  "event PanelChallengeResolved(uint256 indexed taskId,bool upheld)",
  "event EvaluationOutcomesSettled(uint256 indexed taskId,bool approved,uint8 positiveCount,uint8 missedCount)",
  "event ExecutorQualityMultipliersFrozen(uint256 indexed taskId,uint32 indexed workRound,uint32 indexed epoch,uint16[] multipliersBps)",
]);

export const verificationArbitrationCourtAbi = parseAbi([
  "function deposit(uint256 amount)",
  "function withdraw(uint256 amount)",
  "function openChallenge(uint256 taskId,address validator,bytes32 challengeHash)",
  "function vote(uint256 taskId,bool upheld,bytes32 resolutionHash)",
  "function expireChallenge(uint256 taskId)",
  "function getActiveCase(uint256 taskId) view returns (bytes32 caseId,uint64 deadline,bool resolved)",
  "function stake(address) view returns (uint256)",
  "function lockedStake(address) view returns (uint256)",
  "function falseChallengeCount(address) view returns (uint8)",
  "function activeCaseId(uint256 taskId) view returns (bytes32)",
  "event VerificationChallengeOpened(uint256 indexed taskId,bytes32 indexed caseId,address indexed challenger,address validator,bytes32 challengeHash,uint64 deadline)",
  "event VerificationChallengeVote(uint256 indexed taskId,bytes32 indexed caseId,address indexed arbitrator,bool upheld,bytes32 resolutionHash)",
  "event VerificationChallengeResolved(uint256 indexed taskId,bytes32 indexed caseId,bool upheld,bytes32 resolutionHash,uint256 challengerSlash,uint256 validatorSlash,uint256 challengerReward)",
  "event VerificationChallengeExpired(uint256 indexed taskId,bytes32 indexed caseId)",
]);

export const rewardVaultAbi = parseAbi([
  "function claim(uint256 taskId,uint8 checkpoint)",
  "function getGrant(uint256 taskId) view returns ((address[] executors,uint16[] executorWeightsBps,address tester,uint256 startedAt,uint256 total,uint256[4] amounts,bool[4] approved,bool[4] claimed))",
  "function getCheckpointParticipants(uint256 taskId,uint8 checkpoint) view returns (address[] executors,uint16[] weights,address tester)",
  "function dueAt(uint256 startedAt,uint8 checkpoint) pure returns (uint256)",
  "function checkpointDueAt(uint256 taskId,uint8 checkpoint) view returns (uint256)",
  "function getTesterPanel(uint256 taskId) view returns (address[3] testers,uint16[3] weightsBps)",
  "function getCheckpointTesterPanel(uint256 taskId,uint8 checkpoint) view returns (address[3] testers,uint16[3] weightsBps)",
  "event GrantCreated(uint256 indexed taskId,uint256 grossReward,uint256 multiplierBps,bytes32 issuanceProof)",
  "event FutureParticipantsUpdated(uint256 indexed taskId,uint8 indexed fromCheckpoint,address[] executors,uint16[] executorWeightsBps,address tester,bytes32 indexed executorWeightsHash)",
  "event CheckpointApproved(uint256 indexed taskId,uint8 indexed checkpoint)",
  "event RewardClaimed(uint256 indexed taskId,uint8 indexed checkpoint,uint256 amount)",
  "event ExecutorRewardPaid(uint256 indexed taskId,uint8 indexed checkpoint,address indexed executor,uint256 amount)",
  "event EvaluationFeeRegistered(uint256 indexed taskId,uint256 amount)",
  "event EvaluationFeePaid(uint256 indexed taskId,address indexed evaluator,uint256 amount)",
  "event EvaluationFeeSettled(uint256 indexed taskId,uint256 reporterCount,uint256 reserveAmount)",
]);

export const protocolEconomicsAbi = parseAbi([
  "function commitNextTaskSource(bytes32 sourceId)",
  "function claimVesting(bytes32 vestingId)",
  "function taskSources(uint256 taskId) view returns (bytes32 sourceId,address recipient,uint64 frozenAt)",
  "function consumedLifecycleStages(uint256 taskId) view returns (uint8)",
  "function taskRewardRouted(uint256 taskId) view returns (bool)",
  "function vestings(bytes32 vestingId) view returns (address recipient,uint128 amount,uint64 unlockAt,bool claimed)",
  "event TaskSourceFrozen(uint256 indexed taskId,bytes32 indexed requestedSourceId,bytes32 indexed effectiveSourceId,address recipient,bool fallbackToDao)",
  "event TaskRewardRouted(uint256 indexed taskId,uint256 grossReward,uint256 agentPool,uint256 daoAmount,uint256 sourceAmount,bytes32 daoVestingId,bytes32 sourceVestingId)",
  "event LifecycleChargeRouted(uint256 indexed taskId,uint8 indexed stage,uint256 stakeBasis,uint256 amount,uint256 rewardVaultAmount,uint256 burnAmount,uint256 daoAmount,uint256 sourceAmount,uint256 securityAmount,bytes32 daoVestingId,bytes32 sourceVestingId)",
  "event VestingCreated(bytes32 indexed vestingId,address indexed recipient,uint256 amount,uint256 unlockAt)",
  "event VestingClaimed(bytes32 indexed vestingId,address indexed recipient,uint256 amount)",
]);
