import { parseAbi } from "viem";

export const tokenAbi = parseAbi([
  "function balanceOf(address) view returns (uint256)",
  "function allowance(address,address) view returns (uint256)",
  "function approve(address,uint256) returns (bool)",
  "function faucet()",
]);

export const stakeManagerAbi = parseAbi([
  "function createPosition(uint256 amount) returns (uint256)",
  "function issueCredit(uint256 positionId)",
  "function ownerOf(uint256) view returns (address)",
  "function stakeOf(uint256) view returns (uint256)",
  "function TASK_COLLATERAL() view returns (uint256)",
  "function availableTaskCollateral(uint256) view returns (uint256)",
  "function taskLocks(uint256 positionId,uint256 taskId) view returns (bool)",
  "function taskLockCount(uint256 positionId) view returns (uint256)",
  "function agentRegistry() view returns (address)",
  "event PositionCreated(uint256 indexed positionId,address indexed owner,uint256 amount)",
  "event CreditIssued(uint256 indexed positionId,uint256 expiresAt)",
  "event CreditConsumed(uint256 indexed positionId,uint256 indexed taskId)",
  "event PositionReleased(uint256 indexed positionId,uint256 indexed taskId)",
  "event ParticipantPositionLocked(uint256 indexed positionId,uint256 indexed taskId,address indexed participant,uint256 collateral)",
  "event ParticipantPositionUnlocked(uint256 indexed positionId,uint256 indexed taskId,address indexed participant,uint256 collateral)",
  "event PositionSlashed(uint256 indexed positionId,uint256 indexed taskId,uint256 amount,address indexed recipient)",
  "event PublicationFeeCharged(uint256 indexed positionId,uint256 indexed taskId,uint256 amount,address indexed recipient)",
  "event EvaluationFeeCharged(uint256 indexed positionId,uint256 indexed taskId,uint256 amount,address indexed recipient)",
  "event PositionWithdrawn(uint256 indexed positionId,address indexed owner,uint256 amount)",
]);

export const agentRegistryAbi = parseAbi([
  "function register(uint256 positionId)",
  "function registerWithCapabilities(uint256 positionId,uint8 capabilities)",
  "function agentCapabilities(address) view returns (uint8)",
  "function isEligibleFor(address,uint8) view returns (bool)",
  "function agentPosition(address) view returns (uint256)",
  "function isEligible(address) view returns (bool)",
  "function agentCount() view returns (uint256)",
  "function agentAt(uint256) view returns (address)",
  "function registryHash() view returns (bytes32)",
  "function taskRegistry() view returns (address)",
  "function taskPosition(uint256 taskId,address participant) view returns (uint256)",
  "event AgentRegistered(address indexed agent,uint256 indexed positionId,uint256 stake)",
  "event AgentCapabilitiesUpdated(address indexed agent,uint8 capabilities)",
]);

export const taskRegistryAbi = parseAbi([
  "function createTaskWithMode(uint256 positionId,bytes32 specHash,uint256 requestedReward,uint8 maxExecutors,uint8 mode) returns (uint256)",
  "function createTaskWithModeAndTesterCapabilities(uint256 positionId,bytes32 specHash,uint256 requestedReward,uint8 maxExecutors,uint8 mode,uint8 requiredTesterCapabilities) returns (uint256)",
  "function taskRequiredTesterCapabilities(uint256 taskId) view returns (uint8)",
  "function finalizeEvaluationPanel(uint256 taskId)",
  "function submitEvaluation(uint256 taskId,bytes32 categoryHash,uint16 difficultyBps,uint32 estimatedHours,uint16 testabilityBps,uint256 recommendedReward,bool approve,bytes32 reportHash)",
  "function finalizeTaskEvaluation(uint256 taskId)",
  "function expireTaskEvaluation(uint256 taskId)",
  "function getTaskEvaluators(uint256 taskId) view returns (address[3])",
  "function evaluationSelections(uint256 taskId) view returns (uint256 selectionBlock,uint256 candidateCount,uint256 deadline,bytes32 candidateSetHash,bytes32 selectionProof,uint8 reportCount,uint8 approveCount,bool panelFinalized)",
  "function evaluationResults(uint256 taskId) view returns (bytes32 categoryHash,uint16 difficultyBps,uint32 estimatedHours,uint16 testabilityBps,uint256 recommendedReward)",
  "function claimTask(uint256 taskId)",
  "function closeTeam(uint256 taskId)",
  "function evictInactiveExecutor(uint256 taskId,address executor)",
  "function executorClaimedAt(uint256 taskId,address executor) view returns (uint256)",
  "function contributionRound(uint256 taskId,address executor) view returns (uint32)",
  "function teamFormationStartedAt(uint256 taskId) view returns (uint256)",
  "function submitContribution(uint256 taskId,bytes32 contributionHash)",
  "function submitWork(uint256 taskId,bytes32 artifactHash)",
  "function getTaskExecutors(uint256 taskId) view returns (address[])",
  "function nextTaskId() view returns (uint256)",
  "function tasks(uint256 taskId) view returns (address publisher,address executor,address tester,uint256 positionId,uint256 requestedReward,uint256 createdAt,bytes32 specHash,bytes32 artifactHash,bytes32 evidenceHash,bytes32 candidateSetHash,bytes32 selectionProof,uint256 testerSelectionBlock,uint256 testerCandidateCount,bytes32 teamHash,uint8 maxExecutors,uint8 executorCount,uint8 contributionCount,uint32 workRound,bool teamClosed,uint8 state)",
  "function requestTester(uint256 taskId)",
  "function finalizeTester(uint256 taskId)",
  "function testerDeadline(uint256 taskId) view returns (uint256)",
  "function userReviewDeadline(uint256 taskId) view returns (uint256)",
  "function replaceInactiveTester(uint256 taskId)",
  "function finalizeSilentPublisherReview(uint256 taskId)",
  "function setCoordinator(address newCoordinator)",
  "function setDisputeResolver(address newResolver)",
  "function publicationFeeFor(uint256 positionId,uint256 requestedReward) view returns (uint256)",
  "function taskPublicationFee(uint256 taskId) view returns (uint256)",
  "function submitTest(uint256 taskId,bool passed,bytes32 evidenceHash,uint16[] executorWeightsBps)",
  "function submitCompetitionTest(uint256 taskId,bool passed,address winner,bytes32 selectedArtifactHash,bytes32 evidenceHash,uint16[] executorWeightsBps)",
  "function getTaskExecutorWeightsBps(uint256 taskId) view returns (uint16[])",
  "function review(uint256 taskId,bool accepted,bytes32 reasonHash)",
  "function respondToRejection(uint256 taskId,bytes32 responseHash)",
  "function validateMaintenance(uint256 taskId,uint8 checkpoint,bool passed,bytes32 evidenceHash)",
  "function resolveRejection(uint256 taskId,bool executorWins,bytes32 resolutionHash)",
  "event TaskCreated(uint256 indexed taskId,address indexed publisher,uint256 indexed positionId,bytes32 specHash)",
  "event TaskExecutionModeSet(uint256 indexed taskId,uint8 mode)",
  "event TaskTesterCapabilitiesSet(uint256 indexed taskId,uint8 requiredCapabilities)",
  "event TaskEvaluationRequested(uint256 indexed taskId,address indexed publisher,uint256 indexed positionId,bytes32 specHash,uint256 selectionBlock,bytes32 candidateSetHash,uint256 candidateCount,uint256 deadline)",
  "event TaskEvaluationFeeCharged(uint256 indexed taskId,uint256 indexed positionId,uint256 amount,address indexed recipient)",
  "event TaskEvaluatorsAssigned(uint256 indexed taskId,address indexed evaluator0,address indexed evaluator1,address evaluator2,bytes32 selectionProof)",
  "event TaskEvaluationSubmitted(uint256 indexed taskId,address indexed evaluator,bool approve,bytes32 indexed categoryHash,bytes32 reportHash)",
  "event TaskEvaluationFinalized(uint256 indexed taskId,bool approved,bytes32 categoryHash,uint16 difficultyBps,uint32 estimatedHours,uint16 testabilityBps,uint256 requestedReward)",
  "event TaskEvaluationExpired(uint256 indexed taskId)",
  "event TaskPublicationFeeCharged(uint256 indexed taskId,uint256 indexed positionId,uint256 amount,address indexed recipient)",
  "event TaskClaimed(uint256 indexed taskId,address indexed executor)",
  "event ExecutorEvicted(uint256 indexed taskId,address indexed executor)",
  "event TeamClosed(uint256 indexed taskId,uint256 executorCount)",
  "event ContributionSubmitted(uint256 indexed taskId,address indexed executor,uint32 indexed workRound,bytes32 contributionHash)",
  "event TeamReady(uint256 indexed taskId,address indexed leadExecutor,uint32 indexed workRound)",
  "event CompetitionReady(uint256 indexed taskId,uint32 indexed workRound,uint256 candidateCount)",
  "event WorkSubmitted(uint256 indexed taskId,bytes32 artifactHash)",
  "event TesterRequested(uint256 indexed taskId,uint256 indexed selectionBlock,bytes32 candidateSetHash,uint256 candidateCount)",
  "event TesterAssigned(uint256 indexed taskId,address indexed tester,bytes32 selectionProof)",
  "event TestSubmitted(uint256 indexed taskId,bool passed,bytes32 evidenceHash)",
  "event CompetitionResultSubmitted(uint256 indexed taskId,bool passed,address indexed winner,bytes32 artifactHash,bytes32 evidenceHash)",
  "event UserReviewed(uint256 indexed taskId,bool accepted,bytes32 reasonHash)",
  "event RejectionResponded(uint256 indexed taskId,address indexed executor,bytes32 responseHash)",
  "event MaintenanceValidated(uint256 indexed taskId,uint8 indexed checkpoint,bool passed,bytes32 evidenceHash)",
  "event MaintenanceRepairRequested(uint256 indexed taskId,uint8 indexed checkpoint,uint32 indexed workRound,bytes32 evidenceHash)",
  "event RejectionResolved(uint256 indexed taskId,bool executorWins,bytes32 resolutionHash,uint256 publisherSlash)",
]);

export const rewardVaultAbi = parseAbi([
  "function claim(uint256 taskId,uint8 checkpoint)",
  "function getGrant(uint256 taskId) view returns ((address[] executors,uint16[] executorWeightsBps,address tester,uint256 startedAt,uint256 total,uint256[4] amounts,bool[4] approved,bool[4] claimed))",
  "function getCheckpointParticipants(uint256 taskId,uint8 checkpoint) view returns (address[] executors,uint16[] weights,address tester)",
  "function dueAt(uint256 startedAt,uint8 checkpoint) pure returns (uint256)",
  "function checkpointDueAt(uint256 taskId,uint8 checkpoint) view returns (uint256)",
  "event GrantCreated(uint256 indexed taskId,uint256 grossReward,uint256 multiplierBps,bytes32 issuanceProof)",
  "event FutureParticipantsUpdated(uint256 indexed taskId,uint8 indexed fromCheckpoint,address[] executors,uint16[] executorWeightsBps,address tester,bytes32 indexed executorWeightsHash)",
  "event CheckpointApproved(uint256 indexed taskId,uint8 indexed checkpoint)",
  "event RewardClaimed(uint256 indexed taskId,uint8 indexed checkpoint,uint256 amount)",
  "event ExecutorRewardPaid(uint256 indexed taskId,uint8 indexed checkpoint,address indexed executor,uint256 amount)",
  "event EvaluationFeeRegistered(uint256 indexed taskId,uint256 amount)",
  "event EvaluationFeePaid(uint256 indexed taskId,address indexed evaluator,uint256 amount)",
  "event EvaluationFeeSettled(uint256 indexed taskId,uint256 reporterCount,uint256 reserveAmount)",
]);
