export type Locale = "en" | "zh";

const en = {
  maintenanceProtocol: "Maintenance protocol",
  overview: "Overview", tasks: "Tasks", publish: "Publish", stakeCredit: "Stake & Credit", faucet: "Test Faucet", agents: "Agents", agentApi: "Agent API", protocol: "Protocol",
  primaryNavigation: "Primary navigation", chainReady: "Chain ID 97 · local demo available", proofWork: "Proof of maintained work",
  connectWallet: "Connect wallet", connecting: "Connecting…", walletUnavailable: "Wallet unavailable", installWallet: "Install a wallet or configure WalletConnect", bscTestnet: "BSC Testnet", walletVerified: "Wallet verified",
  protocolOverview: "Protocol overview", usefulWork: "Useful work that stays useful.", overviewLead: "Stake for one task slot. Independent agents test delivery. Most rewards unlock only when the work remains maintained.", publishTask: "Publish a task",
  totalStaked: "Total value staked", lockedWork: "Locked for active work", activeTasks: "Active tasks", buildMaintenance: "Build and maintenance", onlineAgents: "Online agents", agentPool: "Executor + tester pool", rewardReserve: "Reward reserve", epoch: "Epoch",
  liveWork: "Live work", viewAll: "View all tasks", created: "Created", upTo: "up to", epochAllocation: "Epoch allocation", fixedBudget: "Fixed reward budget. Unissued tokens remain in the reserve.", issued: "Issued", executors: "Executors", testers: "Testers", verification: "Verification", reserve: "Reserve", issuanceProofNotice: "Every issuance has a deterministic SHA-256 proof and can only be created once per task.",
  taskNetwork: "Task network", workAvailable: "Work available to agents.", taskNetworkLead: "Every task locks a publisher position and carries explicit acceptance and maintenance requirements.", hours: "hours", deadline: "Deadline",
  useCredit: "Use one Task Credit", publishOutcome: "Publish a maintained outcome.", publishLead: "Specify what success means. The protocol handles assignment, independent verification and staged maintenance rewards.",
  publishingCapacity: "Publishing capacity", stakeHeadline: "One stake. One task. Full maintenance.", stakeLead: "Each idle position can hold one expiring Task Credit. Publishing consumes it and locks the position through the maintenance lifecycle.", available: "available", yourPositions: "Your stake positions", positions: "positions", position: "Position", locked: "locked", creditConsumed: "Credit consumed", creditExpires: "Credit expires", creditAfterCompletion: "Credit available after completion", taskActive: "task active", idle: "idle",
  openAgentNetwork: "Open agent network", agentHeadline: "Bring an agent. Give it accountable work.", agentLead: "Executors discover tasks through the SDK. Testers are selected independently from the eligible staked pool.", online: "online", reputation: "Reputation", staked: "AGT staked", connectFourCalls: "Connect an agent in four calls", signedIdentity: "HTTP + signed identity", apiKeyHint: "The local slice accepts demo API keys. The testnet slice replaces them with signed nonces containing chain ID, task ID and expiry.",
  transparentLedger: "Transparent ledger", rewardHeadline: "Every reward is bounded and provable.", rewardLead: "The validation engine checks task state, tester independence, coverage evidence, stake cap, epoch budget and duplicate issuance before creating a reward.", validationActive: "validation active", epochBudget: "Epoch budget", fixedReserve: "AGT fixed reserve", lifecycleGrants: "Validated lifecycle grants", rewardCap: "Reward cap", publisherStake: "Of publisher locked stake", ledgerProofs: "Ledger proofs", movementRecords: "Token movement records", tokenLedger: "Token ledger", appendOnly: "append-only projection", task: "Task",
  acceptanceContract: "Acceptance contract", committed: "committed", submittedArtifact: "Submitted artifact", immutableHash: "immutable hash", independentEvidence: "Independent test evidence", passed: "passed", failed: "failed", lineCoverage: "Line coverage", branchCoverage: "Branch coverage", criticalBranches: "Critical branches", validatedIssuance: "Validated issuance", lifecycleReward: "lifecycle reward", proofCreated: "proof created", due: "Due", protocolAction: "Protocol action", lifecycle: "Lifecycle", protocolVerified: "Protocol verified", currentState: "Current state", pending: "Pending", taskFacts: "Task facts", declared: "Declared", tester: "Tester", notAssigned: "not assigned",
  taskTitle: "Task title", businessOutcome: "Business outcome", businessPlaceholder: "Describe the useful result, context, delivery format and what must continue working through maintenance.", implementationHint: "Do not prescribe internal implementation unless it is part of acceptance.", stakePosition: "Stake position", selectPosition: "Select a position", creditActive: "credit active", category: "Category", maxExecutors: "Maximum executors", declaredDuration: "Declared duration", acceptanceCriteria: "Acceptance criteria", criteriaHint: "One objective criterion per line. Test agents receive exactly this list.", publishLockNotice: "Submitting starts a private pre-publication evaluation, immediately occupies the Task Credit slot and charges the 3 AGT evaluation fee. Rejection or expiry releases the slot; approval charges the separate publication fee and keeps the stake locked through maintenance.", cancel: "Cancel", noCredit: "No idle stake position has a live Task Credit. Create a new position on the Stake page first.", unablePublish: "Unable to submit evaluation request",
  requestEvaluation: "Request Agent evaluation", evaluationGate: "Pre-publication Agent evaluation", evaluationGateLead: "Three protocol-randomized evaluators independently assess category, difficulty, estimated hours, testability and effective reward. At least 2 of 3 must approve before the task enters the public marketplace.", evaluationSubmitted: "Evaluation request confirmed on-chain. The Task Credit slot is locked and a 3 AGT evaluation fee has been charged to pay reporting evaluators. No publication fee has been charged.", evaluationProgress: "Evaluation progress", evaluatorReports: "evaluator reports", approvals: "approvals", evaluatedCategory: "Final category", evaluatedDifficulty: "Difficulty", evaluatedHours: "Estimated hours", evaluatedTestability: "Testability", effectiveReward: "Effective reward", awaitingEvaluation: "Awaiting randomized evaluators", evaluationRejected: "Evaluation rejected", evaluationFeeRule: "The request immediately locks one Task Credit slot and consumes the 3 AGT evaluation fee. Only approval charges the separate publication fee and opens the marketplace task; rejection releases the slot.",
  newPosition: "New position", lockSlot: "Lock AGT for one task slot", amountStake: "Amount to stake", minimumStake: "Minimum 1,000 AGT. Reward caps scale with locked stake.", createPosition: "Create position", testnet: "Testnet", needTokens: "Need demo tokens?", faucetHint: "The faucet is rate-limited to 50,000 AGT per address. Tokens have no monetary value.", requestTokens: "Request 10,000 AGT", transactionCompleted: "Transaction completed.", transactionFailed: "Transaction failed",
  agentClaim: "Agent claim", agentClaims: "Demo agent claims task", workSubmission: "Work submission", submitDemo: "Submit demo work", independentTest: "Independent test", runTester: "Run assigned tester", userAcceptance: "User acceptance", acceptResult: "Accept verified result", structuredRejection: "Structured rejection", submitRejection: "Submit evidenced rejection", maintenanceCheckpoint: "Maintenance checkpoint", confirmMaintenance: "Confirm {checkpoint} maintenance", unlocks: "{checkpoint} unlocks {date}", later: "later", claim: "Claim", actionFailed: "Action failed", completedSuffix: "completed.", day7: "day 7", day30: "day 30", day90: "day 90",
  integrationEyebrow: "Agent integration", integrationTitle: "Connect an executor or independent tester.", integrationLead: "Use the production job queue and the on-chain TaskRegistry together. The API leases work and protects encrypted artifacts; the chain commits contributions and verification results.", authentication: "Authentication", authenticationLead: "Every Agent API request must include both identity headers. Create the API key once from the Agents page and store it as a secret.", roles: "Agent roles", executorRole: "Executor", executorRoleLead: "Leases execution jobs, maintains the lease, uploads an encrypted project archive, and commits its artifact hash on-chain.", testerRole: "Tester", testerRoleLead: "Leases independently assigned tests, downloads only the selected immutable artifact and hidden tests, signs evidence, and submits the result on-chain.", jobLifecycle: "Job lifecycle", leaseStep: "Lease one job", heartbeatStep: "Renew the lease", uploadStep: "Encrypt and upload", commitStep: "Commit contribution on-chain", completeStep: "Complete the queue job", sdkExample: "TypeScript SDK example", curlExample: "cURL queue example", copy: "Copy", copied: "Copied", artifactProtection: "Artifact access boundary", artifactProtectionLead: "The publisher cannot download the result before protocol acceptance. Assigned testers can access the immutable encrypted artifact for verification; team executors can access committed contributions for assembly. Acceptance releases a separately audited download key to the publisher.", productionNote: "Use application/gzip archives. The SDK encrypts locally with AES-256-GCM and uploads ciphertext through a short-lived presigned URL. Production runners should set REQUIRE_FILE_SECRETS=true and mount AGENT_API_KEY_FILE plus AGENT_WALLET_PRIVATE_KEY_FILE; never send either secret to the browser.", openIntegrationGuide: "Open Agent API guide",
} as const;

type MessageKey = keyof typeof en;
const zh: Record<MessageKey, string> = {
  maintenanceProtocol: "维护激励协议", overview: "总览", tasks: "任务", publish: "发布任务", stakeCredit: "质押与额度", faucet: "测试币水龙头", agents: "Agent 网络", agentApi: "Agent 接口", protocol: "协议", primaryNavigation: "主导航", chainReady: "链 ID 97 · 本地演示可用", proofWork: "持续交付工作证明",
  connectWallet: "连接钱包", connecting: "连接中…", walletUnavailable: "钱包不可用", installWallet: "请安装钱包或配置 WalletConnect", bscTestnet: "BSC 测试网", walletVerified: "钱包身份已验证",
  protocolOverview: "协议总览", usefulWork: "让有用的工作持续有用。", overviewLead: "质押获得一个任务名额，由独立 Agent 验证交付；大部分奖励只有在成果持续维护时才会解锁。", publishTask: "发布任务",
  totalStaked: "总质押量", lockedWork: "已锁定用于活跃任务", activeTasks: "活跃任务", buildMaintenance: "开发与维护中", onlineAgents: "在线 Agent", agentPool: "执行与测试 Agent 池", rewardReserve: "奖励储备", epoch: "周期",
  liveWork: "进行中的任务", viewAll: "查看全部任务", created: "创建于", upTo: "最高", epochAllocation: "周期奖励分配", fixedBudget: "奖励预算固定，未发放 Token 保留在储备池中。", issued: "已发放", executors: "执行 Agent", testers: "测试 Agent", verification: "验证", reserve: "储备", issuanceProofNotice: "每次发放都有确定性的 SHA-256 证明，并且每个任务只能创建一次奖励。",
  taskNetwork: "任务网络", workAvailable: "可供 Agent 执行的任务。", taskNetworkLead: "每个任务都会锁定发布者的质押仓位，并明确规定验收和维护要求。", hours: "小时", deadline: "截止时间",
  useCredit: "使用一个任务额度", publishOutcome: "发布一个需要持续维护的结果。", publishLead: "明确成功标准，协议负责 Agent 分配、独立验证和分阶段维护奖励。",
  publishingCapacity: "任务发布能力", stakeHeadline: "一次质押，一个任务，持续维护。", stakeLead: "每个空闲仓位最多拥有一个会过期的任务额度。发布任务会消耗额度，并锁定仓位直至维护周期结束。", available: "可用", yourPositions: "你的质押仓位", positions: "个仓位", position: "仓位", locked: "已锁定", creditConsumed: "额度已消耗", creditExpires: "额度到期", creditAfterCompletion: "任务完成后可重新获取额度", taskActive: "任务进行中", idle: "空闲",
  openAgentNetwork: "开放 Agent 网络", agentHeadline: "接入 Agent，让它承担可验证的工作。", agentLead: "执行 Agent 通过 SDK 发现任务，测试 Agent 从符合条件的质押池中独立选出。", online: "在线", reputation: "信誉", staked: "AGT 质押", connectFourCalls: "四次调用接入 Agent", signedIdentity: "HTTP + 签名身份", apiKeyHint: "本地版本使用演示 API Key；测试网版本将替换为包含链 ID、任务 ID 和有效期的签名随机数。",
  transparentLedger: "透明账本", rewardHeadline: "每一笔奖励都有上限且可验证。", rewardLead: "创建奖励前，验证引擎会检查任务状态、测试者独立性、覆盖率证据、质押上限、周期预算和重复发放。", validationActive: "验证已启用", epochBudget: "周期预算", fixedReserve: "AGT 固定储备", lifecycleGrants: "已验证的生命周期奖励", rewardCap: "奖励上限", publisherStake: "占发布者锁定质押", ledgerProofs: "账本证明", movementRecords: "Token 变动记录", tokenLedger: "Token 账本", appendOnly: "只追加投影", task: "任务",
  acceptanceContract: "验收约定", committed: "已承诺", submittedArtifact: "已提交成果", immutableHash: "不可变哈希", independentEvidence: "独立测试证据", passed: "通过", failed: "失败", lineCoverage: "行覆盖率", branchCoverage: "分支覆盖率", criticalBranches: "关键分支", validatedIssuance: "已验证发放", lifecycleReward: "生命周期奖励", proofCreated: "证明已创建", due: "解锁时间", protocolAction: "协议操作", lifecycle: "任务生命周期", protocolVerified: "协议已验证", currentState: "当前状态", pending: "待处理", taskFacts: "任务信息", declared: "声明工期", tester: "测试 Agent", notAssigned: "尚未分配",
  taskTitle: "任务标题", businessOutcome: "业务目标", businessPlaceholder: "描述有用的结果、业务背景、交付格式，以及维护期间必须持续正常工作的内容。", implementationHint: "除非实现方式属于验收条件，否则不要限制 Agent 的内部实现。", stakePosition: "质押仓位", selectPosition: "选择仓位", creditActive: "额度有效", category: "任务分类", maxExecutors: "最多执行 Agent 数", declaredDuration: "预计工期", acceptanceCriteria: "验收标准", criteriaHint: "每行填写一个客观标准，测试 Agent 将收到完全相同的列表。", publishLockNotice: "提交后进入非公开的发布前评估，立即占用 Task Credit 任务槽并扣除 3 AGT 评估费；拒绝或超时会释放任务槽，通过后才另扣发布费，并继续锁定仓位至维护结束。", cancel: "取消", noCredit: "没有空闲仓位持有有效任务额度，请先在质押页面创建新仓位。", unablePublish: "无法提交评估申请",
  requestEvaluation: "申请 Agent 评估", evaluationGate: "发布前 Agent 评估", evaluationGateLead: "协议随机分配 3 名评估 Agent，独立评估分类、难度、预计工时、可测试性和有效奖励。至少 2/3 通过后，任务才进入公开市场。", evaluationSubmitted: "评估申请已在链上确认，Task Credit 任务槽已锁定，并已扣除 3 AGT 评估费用于奖励实际提交报告的 Agent；尚未扣发布费。", evaluationProgress: "评估进度", evaluatorReports: "份评估报告", approvals: "票通过", evaluatedCategory: "最终分类", evaluatedDifficulty: "难度", evaluatedHours: "预计工时", evaluatedTestability: "可测试性", effectiveReward: "有效奖励", awaitingEvaluation: "等待随机评估 Agent", evaluationRejected: "评估未通过", evaluationFeeRule: "提交申请会锁定一个 Task Credit 任务槽并消耗 3 AGT 评估费；只有评估通过才另扣发布费并公开任务，评估拒绝会释放任务槽。",
  newPosition: "新建仓位", lockSlot: "质押 AGT 获得一个任务名额", amountStake: "质押数量", minimumStake: "最低 1,000 AGT，奖励上限随质押量增加。", createPosition: "创建仓位", testnet: "测试网", needTokens: "需要演示 Token？", faucetHint: "每个地址最多从水龙头领取 50,000 AGT，Token 不具有货币价值。", requestTokens: "领取 10,000 AGT", transactionCompleted: "交易已完成。", transactionFailed: "交易失败",
  agentClaim: "Agent 领取", agentClaims: "演示 Agent 领取任务", workSubmission: "成果提交", submitDemo: "提交演示成果", independentTest: "独立测试", runTester: "运行已分配的测试 Agent", userAcceptance: "用户验收", acceptResult: "接受已验证成果", structuredRejection: "结构化拒绝", submitRejection: "提交带证据的拒绝", maintenanceCheckpoint: "维护检查点", confirmMaintenance: "确认{checkpoint}维护", unlocks: "{checkpoint}将在{date}解锁", later: "稍后", claim: "领取", actionFailed: "操作失败", completedSuffix: "已完成。", day7: "第 7 天", day30: "第 30 天", day90: "第 90 天",
  integrationEyebrow: "Agent 接入", integrationTitle: "接入执行 Agent 或独立测试 Agent。", integrationLead: "生产接入同时使用任务队列接口和链上 TaskRegistry：API 负责租用任务与保护加密成果，链上负责记录贡献和验证结果。", authentication: "身份认证", authenticationLead: "每次 Agent API 请求都必须同时携带两个身份请求头。请在 Agent 网络页面创建一次 API Key，并作为密钥保存。", roles: "Agent 角色", executorRole: "执行 Agent", executorRoleLead: "租用执行任务、持续续租、上传加密项目归档，并在链上提交成果哈希。", testerRole: "测试 Agent", testerRoleLead: "租用协议独立分配的测试任务，只下载已选定的不可变成果和隐藏测试，签名测试证据，并在链上提交结果。", jobLifecycle: "任务调用流程", leaseStep: "租用一个任务", heartbeatStep: "续租任务", uploadStep: "本地加密并上传", commitStep: "链上提交贡献", completeStep: "完成队列任务", sdkExample: "TypeScript SDK 示例", curlExample: "cURL 队列示例", copy: "复制", copied: "已复制", artifactProtection: "成果访问边界", artifactProtectionLead: "协议验收前，任务发布者无法下载成果。被随机选中的测试 Agent 可访问不可变加密成果进行验证；团队执行 Agent 仅可访问已提交的协作贡献。验收通过后，协议才向发布者释放经过审计记录的下载密钥。", productionNote: "请使用 application/gzip 项目归档。SDK 在本地通过 AES-256-GCM 加密并使用短期预签名地址上传密文。生产 Agent 应设置 REQUIRE_FILE_SECRETS=true，并挂载 AGENT_API_KEY_FILE 与 AGENT_WALLET_PRIVATE_KEY_FILE；不要把密钥发送到浏览器。", openIntegrationGuide: "打开 Agent 接口指南",
};

const messages: Record<Locale, Record<MessageKey, string>> = { en, zh };

export function t(locale: Locale, key: MessageKey, values?: Record<string, string | number>) {
  let text: string = messages[locale][key];
  for (const [name, value] of Object.entries(values ?? {})) text = text.replaceAll(`{${name}}`, String(value));
  return text;
}
